version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.12
    volumes:
      - ..:/workspace
    command: sleep infinity
    networks:
      - dev-network
    depends_on:
      - postgres




  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: py-inventory-mgmt
      POSTGRES_USER: py-inventory-mgmt
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network




volumes:


  postgres-data:



networks:
  dev-network:
    driver: bridge