test_name: "Test for py-inventory-mgmt : Design and implement few critical APIs for inventory management"
stages:

  - name: POST request to /sku
    request:
      url: http://py-inventory-mgmt:8000/sku
      method: POST
      headers:
        content-type: application/json
      json:
        sku_code: "TEST123"
        name: "Test Product"
        quantity: 50
        price: 29.99
    response:
      status_code: 200
      strict: false
      headers:
        content-type: application/json
      json:
        sku_id: !anystr
        sku_code: "TEST123"
        name: "Test Product"
        quantity: 50
      save:
        json:
          sku_id: sku_id

  - name: POST request to /sku/{sku_id}/temporary-block
    request:
      url: http://py-inventory-mgmt:8000/sku/{sku_id:s}/temporary-block
      method: POST
      headers:
        content-type: application/json
      json:
        quantity: 10
        reason: "Order processing"
        expires_at: "2024-12-31T23:59:59Z"
    response:
      status_code: 200
      strict: false
      headers:
        content-type: application/json
      json:
        block_id: !anystr
        sku_id: "{sku_id:s}"
        quantity: 10
        reason: "Order processing"
        status: "active"
      save:
        json:
          block_id: block_id

  - name: GET request to /temporary-blocks
    request:
      url: http://py-inventory-mgmt:8000/temporary-blocks
      method: GET
    response:
      status_code: 200
      strict: false
      headers:
        content-type: application/json
      json:
        blocks: !anylist
        total: !anyint

  - name: POST request to /temporary-blocks/{block_id}/convert-to-permanent
    request:
      url: http://py-inventory-mgmt:8000/temporary-blocks/{block_id:s}/convert-to-permanent
      method: POST
      headers:
        content-type: application/json
      json:
        reason: "Order confirmed"
    response:
      status_code: 200
      strict: false
      headers:
        content-type: application/json
      json:
        block_id: "{block_id:s}"
        status: "converted"
        reason: "Order confirmed"
